"use client";

import { useEffect, useState } from "react";
import { PortalHeader } from "./portal-nav";

type AssetState = { sources: Array<Record<string, unknown>>; snapshots: Array<Record<string, unknown>>; history: Array<Record<string, unknown>>; runs: Array<Record<string, unknown>> };
const money = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }); const yen = new Intl.NumberFormat("ja-JP", { maximumFractionDigits: 0 });

export function ManageAssetApp() { const [state, setState] = useState<AssetState | null>(null); const [error,setError]=useState(""); useEffect(()=>{fetch("/api/manage-asset/state").then(async r=>{if(!r.ok)throw new Error("資産データを読み込めませんでした。");setState(await r.json());}).catch(e=>setError(e instanceof Error?e.message:"読み込みに失敗しました。"));},[]); const totalUsd=state?.snapshots.reduce((sum,row)=>sum+Number(row.total_usd??0),0)??0; const totalJpy=state?.snapshots.reduce((sum,row)=>sum+Number(row.total_jpy??0),0)??0; return <main className="portal-shell"><PortalHeader kicker="PRIVATE LEDGER" title="Manage Asset" active="/manage-asset" /><div className="page-toolbar"><p>Macで取得したスナップショットを、ここで閲覧する。</p><span className="sync-pill">APIキーはMacのKeychain内</span></div>{error&&<p className="notice" role="alert">{error}</p>}<section className="asset-hero"><div><span className="card-eyebrow">LATEST TOTAL</span><strong>{state?money.format(totalUsd):"—"}</strong><p>{state?`${yen.format(totalJpy)}円 · ${state.snapshots.length} sources`:"まだ同期されていません"}</p></div><div className="asset-freshness"><span>最終取得</span><strong>{state?.snapshots[0]?.captured_at?new Date(String(state.snapshots[0].captured_at)).toLocaleString("ja-JP"):"未同期"}</strong></div></section><section className="asset-grid"><div className="asset-panel"><div className="panel-heading"><div><p className="app-kicker">LOCATIONS</p><h2>保管場所</h2></div><span>{state?.sources.length??0} sources</span></div>{state?.snapshots.map(row=><div className="asset-row" key={String(row.id)}><div><strong>{String(row.display_name??row.source_id)}</strong><span>{String(row.provider??"")} · {String(row.as_of_date??"")}</span></div><strong>{money.format(Number(row.total_usd??0))}</strong></div>)}{!state?.snapshots.length&&<div className="empty-state"><strong>データがありません。</strong><p>Mac側の同期エージェントから送信してください。</p></div>}</div><div className="asset-panel"><div className="panel-heading"><div><p className="app-kicker">SYNC RUNS</p><h2>同期履歴</h2></div></div>{state?.runs.map(run=><div className="run-row" key={String(run.id)}><span>{String(run.status)}</span><strong>{String(run.received_at).slice(0,16).replace("T"," ")}</strong><small>{String(run.success_count??0)} sources</small></div>)}</div></section></main>; }
