"use client";

import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { PortalHeader } from "./portal-nav";

export type Video = { id:string; title:string; channel_name:string; thumbnail_url:string; original_url:string; summary:string; published_at:string|null; view_count:number; duration:string; created_at:string; updated_at:string; detailed_script_object_key?:string|null };
export type VideoForm = { title:string; channelName:string; originalUrl:string; thumbnailUrl:string; channelThumbnailUrl:string; summary:string; detailedScript:string; publishedAt:string; viewCount:number; duration:string };
export const blankVideo: VideoForm = { title:"", channelName:"", originalUrl:"", thumbnailUrl:"", channelThumbnailUrl:"", summary:"", detailedScript:"", publishedAt:"", viewCount:0, duration:"" };
const date = (value?:string|null) => value ? new Date(value).toLocaleDateString("ja-JP") : "—";
const views = (value:number) => value >= 10000 ? `${(value/10000).toFixed(1)}万` : value.toLocaleString("ja-JP");

export function TextTubeApp() {
  const [videos,setVideos] = useState<Video[]>([]); const [q,setQ] = useState(""); const [channel,setChannel] = useState("all"); const [sort,setSort] = useState("created_at-desc"); const [open,setOpen] = useState(false); const [notice,setNotice] = useState("");
  async function load(){ const r=await fetch(`/api/text-tube/videos?q=${encodeURIComponent(q)}`); if(r.ok) setVideos((await r.json()).videos); }
  useEffect(()=>{ const t=setTimeout(load,q?180:0); return()=>clearTimeout(t); },[q]);
  const channels=useMemo(()=>Array.from(new Set(videos.map(v=>v.channel_name).filter(Boolean))).sort(),[videos]);
  const shown=useMemo(()=>videos.filter(v=>channel==="all"||v.channel_name===channel).sort((a,b)=>{if(sort==="title-asc")return a.title.localeCompare(b.title);if(sort==="view_count-desc")return b.view_count-a.view_count;if(sort==="created_at-asc")return a.created_at.localeCompare(b.created_at);return b.created_at.localeCompare(a.created_at)}),[videos,channel,sort]);
  async function create(event:FormEvent){event.preventDefault();const r=await fetch("/api/text-tube/videos",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(formToPayload(form))});const d=await r.json();if(!r.ok){setNotice(d.error??"保存できませんでした。");return}if(form.detailedScript)await fetch(`/api/text-tube/videos/${d.id}/document`,{method:"POST",body:form.detailedScript});setNotice("動画を追加しました。");setForm(blankVideo);setOpen(false);await load()}
  const [form,setForm]=useState<VideoForm>(blankVideo);
  return <main className="portal-shell"><PortalHeader kicker="READING ROOM / LIBRARY" title="TextTube" active="/text-tube"/><div className="page-toolbar"><div><p>動画を読むための個人ライブラリ。</p><div className="summary-grid"><span>{videos.length} 本</span><span>{channels.length} チャンネル</span></div></div><div className="header-actions"><Link className="secondary-button" href="/text-tube/studio">Studioを開く</Link><button className="add-button" onClick={()=>setOpen(true)}>＋ 動画を追加</button></div></div>{notice&&<p className="notice" role="status">{notice}</p>}<section className="library-panel"><div className="library-heading"><div><p className="app-kicker">VIDEO LIBRARY</p><h2>おすすめの要約</h2></div><span className="result-count">{shown.length} 件表示</span></div><div className="filters"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="タイトル・概要・チャンネルを検索"/><select value={channel} onChange={e=>setChannel(e.target.value)}><option value="all">すべてのチャンネル</option>{channels.map(c=><option key={c}>{c}</option>)}</select><select value={sort} onChange={e=>setSort(e.target.value)}><option value="created_at-desc">記事作成日が新しい順</option><option value="view_count-desc">閲覧数が多い順</option><option value="created_at-asc">古い順</option><option value="title-asc">タイトル順</option></select></div><div className="video-grid">{shown.map(video=><Link href={`/text-tube/watch/${video.id}`} className="video-card" key={video.id}><div className="video-thumb">{video.thumbnail_url?<img src={video.thumbnail_url} alt=""/>:<span>TEXT TUBE</span>} {video.duration&&<b>{video.duration}</b>}</div><div className="video-card-body"><div className="channel-dot">{(video.channel_name||"T").slice(0,1)}</div><div><h3>{video.title}</h3><p>{video.channel_name||"チャンネル未設定"}</p><small>{views(video.view_count)} 閲覧 · 作成 {date(video.created_at)} · 公開 {date(video.published_at)}</small></div></div></Link>)}{shown.length===0&&<div className="empty-state"><strong>該当する動画がありません。</strong><p>検索条件を変えるか、Studioから追加してください。</p></div>}</div></section>{open&&<VideoEditor title="動画を追加" value={form} onChange={setForm} onClose={()=>setOpen(false)} onSubmit={create} submitLabel="追加する"/>}</main>;
}
export function formToPayload(form:VideoForm){return {title:form.title,channelName:form.channelName,originalUrl:form.originalUrl,thumbnailUrl:form.thumbnailUrl,channelThumbnailUrl:form.channelThumbnailUrl,summary:form.summary,publishedAt:form.publishedAt,viewCount:form.viewCount,duration:form.duration};}
export function VideoEditor({title,value,onChange,onClose,onSubmit,submitLabel}:{title:string;value:VideoForm;onChange:(v:VideoForm)=>void;onClose:()=>void;onSubmit:(e:FormEvent)=>void;submitLabel:string}){const set=(key:keyof VideoForm)=>(e:React.ChangeEvent<HTMLInputElement|HTMLTextAreaElement>)=>onChange({...value,[key]:key==="viewCount"?Number(e.target.value):e.target.value});return <div className="modal-backdrop"><section className="editor" role="dialog" aria-modal="true"><div className="editor-heading"><div><p className="app-kicker">TEXTTUBE STUDIO</p><h2>{title}</h2></div><button className="close-button" onClick={onClose}>×</button></div><form onSubmit={onSubmit}><label className="title-field">タイトル <b>必須</b><input required value={value.title} onChange={set("title")}/></label><div className="form-grid"><label>チャンネル<input value={value.channelName} onChange={set("channelName")}/></label><label>動画URL<input type="url" value={value.originalUrl} onChange={set("originalUrl")}/></label><label>サムネイルURL<input type="url" value={value.thumbnailUrl} onChange={set("thumbnailUrl")}/></label><label>チャンネル画像URL<input type="url" value={value.channelThumbnailUrl} onChange={set("channelThumbnailUrl")}/></label><label>公開日<input type="date" value={value.publishedAt?.slice(0,10)} onChange={set("publishedAt")}/></label><label>動画時間<input placeholder="12:34" value={value.duration} onChange={set("duration")}/></label><label>閲覧数<input type="number" min="0" value={value.viewCount} onChange={set("viewCount")}/></label></div><label>要約<textarea rows={7} value={value.summary} onChange={set("summary")}/></label><label>詳細スクリプト（Markdown）<textarea rows={14} value={value.detailedScript} onChange={set("detailedScript")} placeholder="見出しや箇条書きを含む本文"/></label><div className="editor-actions"><button type="button" className="cancel-button" onClick={onClose}>キャンセル</button><button className="save-button">{submitLabel}</button></div></form></section></div>}
