"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { PortalHeader } from "./portal-nav";

type Video = { id: string; title: string; channel_name: string; thumbnail_url: string; original_url: string; summary: string; published_at: string | null; view_count: number; duration: string; created_at: string };
const initial = { title: "", channelName: "", originalUrl: "", thumbnailUrl: "", summary: "", detailedScript: "", publishedAt: "", viewCount: 0, duration: "" };

export function TextTubeApp() {
  const [videos, setVideos] = useState<Video[]>([]); const [q, setQ] = useState(""); const [form, setForm] = useState(initial); const [open, setOpen] = useState(false); const [notice, setNotice] = useState("");
  async function load() { const response = await fetch(`/api/text-tube/videos?q=${encodeURIComponent(q)}`); if (response.ok) setVideos((await response.json()).videos); }
  useEffect(() => { const timer = setTimeout(load, q ? 180 : 0); return () => clearTimeout(timer); }, [q]);
  async function create(event: FormEvent) { event.preventDefault(); const response = await fetch("/api/text-tube/videos", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(form) }); const data = await response.json(); if (!response.ok) { setNotice(data.error ?? "保存できませんでした。"); return; } setNotice("動画を追加しました。"); setForm(initial); setOpen(false); await load(); }
  return <main className="portal-shell"><PortalHeader kicker="READING ROOM" title="TextTube" active="/text-tube" /><div className="page-toolbar"><p>YouTubeの内容を、読むために保存する。</p><button className="add-button" onClick={() => setOpen(true)}>＋ 動画を追加</button></div>{notice && <p className="notice" role="status">{notice}</p>}<section className="tube-panel"><div className="panel-heading"><div><p className="app-kicker">VIDEO LIBRARY</p><h2>動画一覧</h2></div><input className="wide-search" value={q} onChange={(event) => setQ(event.target.value)} placeholder="タイトル、チャンネルを検索" aria-label="動画を検索" /></div><div className="video-grid">{videos.map((video) => <Link href={`/text-tube/watch/${video.id}`} className="video-card" key={video.id}><div className="video-thumb">{video.thumbnail_url ? <img src={video.thumbnail_url} alt="" /> : <span>TEXT</span>}</div><div className="video-card-body"><h3>{video.title}</h3><p>{video.channel_name || "チャンネル未設定"}</p><small>{video.published_at?.slice(0,10) ?? video.created_at.slice(0,10)}{video.duration ? ` · ${video.duration}` : ""}</small></div></Link>)}{videos.length === 0 && <div className="empty-state"><strong>動画がありません。</strong><p>最初の動画を追加してください。</p></div>}</div></section>{open && <div className="modal-backdrop"><section className="editor" role="dialog" aria-modal="true"><div className="editor-heading"><div><p className="app-kicker">NEW VIDEO</p><h2>動画を追加</h2></div><button className="close-button" onClick={() => setOpen(false)} aria-label="閉じる">×</button></div><form onSubmit={create}><label className="title-field"><span>タイトル <b>必須</b></span><input required value={form.title} onChange={(e) => setForm({...form,title:e.target.value})} /></label><div className="form-grid"><label>チャンネル<input value={form.channelName} onChange={(e) => setForm({...form,channelName:e.target.value})} /></label><label>動画URL<input type="url" value={form.originalUrl} onChange={(e) => setForm({...form,originalUrl:e.target.value})} /></label></div><div className="form-grid"><label>サムネイルURL<input type="url" value={form.thumbnailUrl} onChange={(e) => setForm({...form,thumbnailUrl:e.target.value})} /></label><label>公開日<input type="date" value={form.publishedAt} onChange={(e) => setForm({...form,publishedAt:e.target.value})} /></label></div><label>要約<textarea rows={5} value={form.summary} onChange={(e) => setForm({...form,summary:e.target.value})} /></label><div className="editor-actions"><button type="button" className="cancel-button" onClick={() => setOpen(false)}>キャンセル</button><button className="save-button">追加する</button></div></form></section></div>}</main>;
}
