"use client";
import Link from "next/link";
import Image from "next/image";
import { useEffect, useState } from "react";
import { MarkdownRenderer } from "../../markdown-renderer";
import { TextTubeChrome } from "../../../text-tube-app";
import { ApiError, readJson } from "../../../lib/json";
type Video=Record<string,unknown>; const date=(v:unknown)=>v?new Date(String(v)).toLocaleDateString("ja-JP"):"—";
export default function TextTubeWatchPage({params}:{params:Promise<{id:string}>}){const [video,setVideo]=useState<Video|null>(null),[doc,setDoc]=useState(""),[error,setError]=useState("");useEffect(()=>{params.then(({id})=>Promise.all([fetch(`/api/text-tube/videos/${id}`).then(r=>readJson<ApiError&{video:Video}>(r)),fetch(`/api/text-tube/videos/${id}/document`).then(r=>r.ok?r.text():"")]).then(([d,text])=>{if(d.error)throw Error(d.error);setVideo(d.video);setDoc(text)}).catch(e=>setError(e.message)))},[params]);if(error)return <TextTubeChrome><div className="tt-empty">{error}<Link href="/text-tube">一覧に戻る</Link></div></TextTubeChrome>;if(!video)return <TextTubeChrome><div className="tt-loading">読み込み中…</div></TextTubeChrome>;const readTime=Math.max(1,Math.ceil(String(video.summary??"").length/1000));return <TextTubeChrome><div className="tt-reading-layout"><article className="tt-reading-main"><header className="tt-reading-header"><div className="tt-reading-thumb">{Boolean(video.thumbnail_url)&&<Image src={String(video.thumbnail_url)} alt="" fill sizes="(max-width: 700px) 110px, 180px" unoptimized/>}</div><div><h1>{String(video.title)}</h1><div className="tt-reading-meta"><span>{String(video.channel_name||"チャンネル未設定")}</span><span>•</span><span>{date(video.created_at)}</span><span>•</span><strong>要約読了：約{readTime}分</strong></div>{Boolean(video.original_url)&&<a className="tt-source-link" href={String(video.original_url)} target="_blank" rel="noreferrer">元の動画を見る ↗</a>}</div></header><section className="tt-reading-section"><h2>要約</h2><MarkdownRenderer content={String(video.summary||"")}/></section>{doc&&<section className="tt-reading-section"><h2>詳細スクリプト</h2><MarkdownRenderer content={doc}/></section>}</article><aside className="tt-next"><h2>次の動画</h2><Link href="/text-tube"><small>おすすめ</small><b>もっと動画を探す</b></Link><Link href="/text-tube/studio"><small>Studio</small><b>動画を管理する</b></Link></aside></div></TextTubeChrome>}
