"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { PortalHeader } from "../../portal-nav";
import { Video, VideoEditor, blankVideo, formToPayload } from "../../text-tube-app";

const date=(v?:string|null)=>v?new Date(v).toLocaleDateString("ja-JP"):"—";
export default function TextTubeStudio(){
 const [videos,setVideos]=useState<Video[]>([]),[q,setQ]=useState(""),[sort,setSort]=useState("created_at-desc"),[editing,setEditing]=useState<Video|null>(null),[notice,setNotice]=useState("");
 async function load(){const r=await fetch(`/api/text-tube/videos?q=${encodeURIComponent(q)}`);if(r.ok)setVideos((await r.json()).videos)} useEffect(()=>{load()},[q]);
 const sorted=useMemo(()=>videos.slice().sort((a,b)=>sort==="view_count-desc"?b.view_count-a.view_count:sort==="title-asc"?a.title.localeCompare(b.title):sort==="created_at-asc"?a.created_at.localeCompare(b.created_at):b.created_at.localeCompare(a.created_at)),[videos,sort]);
 async function openEdit(video:Video){const r=await fetch(`/api/text-tube/videos/${video.id}`);const d=await r.json();const doc=await fetch(`/api/text-tube/videos/${video.id}/document`).then(x=>x.ok?x.text():"");setEditing({...d.video,detailedScript:doc} as Video&{detailedScript:string})}
 async function save(e:React.FormEvent){e.preventDefault();if(!editing)return;const f=editing as Video&{detailedScript:string};const r=await fetch(`/api/text-tube/videos/${editing.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(formToPayload({title:f.title,channelName:f.channel_name,originalUrl:f.original_url,thumbnailUrl:f.thumbnail_url,channelThumbnailUrl:f.channel_thumbnail_url,summary:f.summary,detailedScript:f.detailedScript,publishedAt:f.published_at??"",viewCount:f.view_count,duration:f.duration}))});if(!r.ok){setNotice("更新できませんでした。");return}await fetch(`/api/text-tube/videos/${editing.id}/document`,{method:"POST",body:f.detailedScript});setEditing(null);setNotice("保存しました。");await load()}
 async function remove(id:string){if(!confirm("この動画を削除しますか？"))return;await fetch(`/api/text-tube/videos/${id}`,{method:"DELETE"});setNotice("削除しました。");await load()}
 return <main className="portal-shell"><PortalHeader kicker="TEXTTUBE / STUDIO" title="Studio デスク" active="/text-tube"/><div className="page-toolbar"><div><p>動画の管理・要約の編集・本文の更新。</p><div className="summary-grid"><span>{videos.length} 本</span><span>{videos.filter(v=>v.detailed_script_object_key).length} 本に本文あり</span></div></div><Link className="add-button" href="/text-tube">← ライブラリへ</Link></div>{notice&&<p className="notice">{notice}</p>}<section className="library-panel"><div className="filters studio-filters"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="管理動画を検索"/><select value={sort} onChange={e=>setSort(e.target.value)}><option value="created_at-desc">作成日が新しい順</option><option value="view_count-desc">閲覧数が多い順</option><option value="created_at-asc">古い順</option><option value="title-asc">タイトル順</option></select></div><div className="table-scroll"><table className="studio-table"><thead><tr><th>動画 / コンテンツ</th><th>閲覧数</th><th>本文</th><th>日付管理</th><th>操作</th></tr></thead><tbody>{sorted.map(v=><tr key={v.id}><td><div className="studio-video"><div className="video-thumb">{v.thumbnail_url?<img src={v.thumbnail_url} alt=""/>:<span>TEXT</span>}</div><div><Link href={`/text-tube/watch/${v.id}`}><strong>{v.title}</strong></Link><small>{v.channel_name||"チャンネル未設定"}</small></div></div></td><td>{v.view_count.toLocaleString("ja-JP")}</td><td><span className={v.detailed_script_object_key?"status-good":"status-muted"}>{v.detailed_script_object_key?"保存済み":"なし"}</span></td><td>{date(v.created_at)}<small>更新 {date(v.updated_at)}</small></td><td><button className="table-action" onClick={()=>openEdit(v)}>編集</button><button className="table-action danger" onClick={()=>remove(v.id)}>削除</button></td></tr>)}</tbody></table></div></section>{editing&&<VideoEditor title="動画を編集" value={{title:editing.title,channelName:editing.channel_name,originalUrl:editing.original_url,thumbnailUrl:editing.thumbnail_url,channelThumbnailUrl:editing.channel_thumbnail_url,summary:editing.summary,detailedScript:(editing as Video&{detailedScript?:string}).detailedScript??"",publishedAt:editing.published_at??"",viewCount:editing.view_count,duration:editing.duration}} onChange={v=>setEditing({...editing,title:v.title,channel_name:v.channelName,original_url:v.originalUrl,thumbnail_url:v.thumbnailUrl,channel_thumbnail_url:v.channelThumbnailUrl,summary:v.summary,published_at:v.publishedAt,view_count:v.viewCount,duration:v.duration,detailedScript:v.detailedScript} as Video&{detailedScript:string})} onClose={()=>setEditing(null)} onSubmit={save} submitLabel="保存する"/>}</main>
}
